CC=gcc
CFLAGS=-W -Wall -ggdb `sdl-config --cflags` `guile-config compile` `pkg-config lua5.1 --cflags`
LIBS=-lm `sdl-config --libs` `guile-config link` -ltcl -lsndfile -lvorbisfile -lvorbis -logg `pkg-config lua5.1 --libs`
INS_DEPS=

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CFLAGS += -lopenal
	INS_DEPS= sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev tcl-dev guile-1.8-dev libopenal-dev libsndfile1-dev libalut-dev
# sudo apt-get install build-essential autotools-dev autoconf vim
endif

ifeq ($(UNAME_S),Darwin)
	LIBS += -framework OpenAL
#	INS_DEPS= brew install sdl sdl_mixer guile libsndfile freealut
# openal, tcl already supported by mac
endif

SRC = $(wildcard *.c)
OBJ = $(patsubst %.c, %.o, $(SRC))

pw: dep $(OBJ)
	$(CC) $(CFLAGS) $(LIBS) $(OBJ) -o pw

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

check-syntax:
	$(CC) $(CFLAGS) -Wall -Wextra -fsyntax-only $(CHK_SOURCES)

default:
	@echo 'Plese check the variables at the top of the Makefile, then run make pw.'

clean:
	rm -f pw $(OBJ)
	rm -f *~

.PHONY: clean default check-syntax

dep:
	@echo 'install depands...'
	$(INS_DEPS)

# support gyp
gyp-make:
	gyp pw.gyp --depth=. -f make --generator-output=./build

gyp-xcode:
	gyp pw.gyp --depth=. -f xcode --generator-output=./build/xcodefiles
